import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { TypeAnimation } from 'react-type-animation';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Image src={'/images/profileswag.png'} alt='Profile Image' layout='fixed' width='150' height='150' />
        <div className='autoTypedAnimationContainer'>
          <TypeAnimation sequence={['Hi', 500, "Hi I'm Piotr Klebaniuk"]} wrapper='p' cursor={true} />
          <TypeAnimation
            sequence={[2600, "I'm Software Developer"]}
            wrapper='p'
            cursor={false}
            style={{ color: '#0070f3' }}
          />
        </div>
      </header>

      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <p>klebaniukp@gmail.com</p>
        <p>klebaniukp</p>

        <div className={styles.flex}>
          <div className={styles.link}>
            <Link passHref href='https://www.linkedin.com/in/piotr-klebaniuk-188548222/'>
              <a target='blank'>
                <Image src={'/images/linkedin.svg'} alt='linkedin logo' width='30' height='30' />
              </a>
            </Link>
          </div>

          <div className={styles.link}>
            <Link passHref href='https://github.com/klebaniukp'>
              <a target='blank'>
                <Image src={'/images/github.svg'} alt='github logo' width='30' height='30' />
              </a>
            </Link>
          </div>

          <div className={styles.link}>
            <Link passHref href='https://twitter.com/PKlebaniuk'>
              <a target='blank'>
                <Image src={'/images/twitter.svg'} alt='twitter logo' width='30' height='30' />
              </a>
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
