import Head from 'next/head';
import Header from '../components/header';
import Footer from '../components/footer';
import styles from '../styles/Home.module.css';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main className={styles.main}></main>
      <Footer />
    </div>
  );
}
